# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='nombre',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='autor',
            new_name='user',
        ),
    ]
